//! Generate `tuile/src/widgets/spinner/spinners.rs`.
//!
//! Sources: `xtask/spinners.json` (yaspin's copy of cli-spinners, 90 spinners) plus the
//! tuile originals defined below, some of which are computed rather than listed.

use serde_json::Value;
use std::fmt::Write as _;

pub fn run() -> Result<(), String> {
    let root = crate::root();
    let json_path = root.join("xtask/spinners.json");
    let out_path = root.join("tuile/src/widgets/spinner/spinners.rs");

    let raw = std::fs::read_to_string(&json_path)
        .map_err(|e| format!("spinners: reading {}: {e}", json_path.display()))?;
    let parsed: Value = serde_json::from_str(&raw).map_err(|e| format!("spinners: {e}"))?;
    let yaspin = parsed.as_object().ok_or("spinners: expected a JSON object")?;

    let originals = originals();
    for (name, _, _) in &originals {
        if yaspin.contains_key(*name) {
            return Err(format!("spinners: original `{name}` clashes with a yaspin name"));
        }
    }

    let mut out = String::from(
        "//! Spinner catalog: every spinner shipped with [yaspin] / cli-spinners plus tuile\n\
         //! originals. Generated by `cargo xtask spinners`; do not edit by hand.\n\
         //!\n\
         //! [yaspin]: https://github.com/pavdmyt/yaspin\n\
         \n\
         use super::SpinnerDef;\n\n",
    );

    for (name, spec) in yaspin {
        let interval = spec["interval"].as_u64().ok_or("spinners: missing interval")?;
        let frames: Vec<String> = spec["frames"]
            .as_array()
            .ok_or("spinners: missing frames")?
            .iter()
            .map(|f| f.as_str().unwrap_or_default().to_string())
            .collect();
        out.push_str(&emit(name, interval, &frames, "yaspin"));
    }
    for (name, interval, frames) in &originals {
        out.push_str(&emit(name, *interval, frames, "tuile"));
    }

    let yaspin_names: Vec<&str> = yaspin.keys().map(String::as_str).collect();
    let original_names: Vec<&str> = originals.iter().map(|(n, _, _)| *n).collect();
    let all: Vec<&str> = yaspin_names.iter().chain(&original_names).copied().collect();

    out.push_str(&table("The yaspin / cli-spinners set, in upstream order.", "YASPIN", &yaspin_names));
    out.push_str(&table("Spinners original to tuile.", "ORIGINALS", &original_names));
    out.push_str(&table("Every spinner: [`YASPIN`] followed by [`ORIGINALS`].", "ALL", &all));

    std::fs::write(&out_path, &out)
        .map_err(|e| format!("spinners: writing {}: {e}", out_path.display()))?;
    println!(
        "wrote {}: {} yaspin + {} originals",
        out_path.strip_prefix(&root).unwrap_or(&out_path).display(),
        yaspin.len(),
        originals.len()
    );
    Ok(())
}

fn emit(name: &str, interval: u64, frames: &[String], origin: &str) -> String {
    let list: Vec<String> = frames.iter().map(|f| rust_str(f)).collect();
    let mut s = String::new();
    let _ = writeln!(s, "/// {origin} `{name}` - {} frames @ {interval} ms.", frames.len());
    let _ = writeln!(
        s,
        "pub const {}: SpinnerDef = SpinnerDef {{ name: {}, interval_ms: {interval}, frames: &[{}] }};",
        const_name(name),
        rust_str(name),
        list.join(", ")
    );
    s.push('\n');
    s
}

fn table(doc: &str, konst: &str, names: &[&str]) -> String {
    let refs: Vec<String> = names.iter().map(|n| format!("&{}", const_name(n))).collect();
    format!("/// {doc}\npub const {konst}: &[&SpinnerDef] = &[{}];\n\n", refs.join(", "))
}

/// `squarePulse` becomes `SQUARE_PULSE`.
fn const_name(name: &str) -> String {
    let mut out = String::new();
    let mut prev_lower = false;
    for c in name.chars() {
        if c.is_ascii_uppercase() && prev_lower {
            out.push('_');
        }
        prev_lower = c.is_ascii_lowercase();
        out.push(c.to_ascii_uppercase());
    }
    out
}

fn rust_str(s: &str) -> String {
    format!("\"{}\"", s.replace('\\', "\\\\").replace('"', "\\\""))
}

/// Linear congruential generator, kept identical so regenerating produces the same catalog.
struct Lcg(u64);

impl Lcg {
    fn next(&mut self) -> u64 {
        self.0 = (self.0.wrapping_mul(1103515245).wrapping_add(12345)) & 0x7FFF_FFFF;
        self.0 >> 16
    }
}

fn originals() -> Vec<(&'static str, u64, Vec<String>)> {
    vec![
        ("sparkle", 90, strs(&["✦", "✧", "✶", "✷", "✸", "✹", "✺", "✹", "✸", "✷", "✶", "✧"])),
        ("ring", 110, strs(&["◌", "○", "◎", "◉", "●", "◉", "◎", "○"])),
        ("diamond", 180, strs(&["◇", "◈", "◆", "◈"])),
        ("squarePulse", 160, strs(&["□", "▢", "▣", "■", "▣", "▢"])),
        ("hourglass", 500, strs(&["⧖", "⧗"])),
        ("wave", 70, wave()),
        ("equalizer", 110, equalizer()),
        ("scanner", 80, scanner()),
        ("shimmer", 70, shimmer()),
        (
            "dna",
            120,
            strs(&["●───○", " ●─○ ", "  ◍  ", " ○─● ", "○───●", " ○─● ", "  ◍  ", " ●─○ "]),
        ),
        ("matrix", 90, matrix()),
        ("brailleWave", 100, strs(&["⣀⠤⠉", "⠤⠉⠤", "⠉⠤⣀", "⠤⣀⠤"])),
    ]
}

fn strs(v: &[&str]) -> Vec<String> {
    v.iter().map(|s| s.to_string()).collect()
}

fn wave() -> Vec<String> {
    let (n, cells) = (7usize, 6usize);
    let glyphs: Vec<char> = "▁▂▃▄▅▆▇".chars().collect();
    (0..n * 2)
        .map(|f| {
            (0..cells)
                .map(|c| {
                    let phase = (c as f64 / cells as f64 + f as f64 / (n * 2) as f64)
                        * 2.0
                        * std::f64::consts::PI;
                    let v = (phase.sin() + 1.0) / 2.0;
                    glyphs[round_half_even(v * (glyphs.len() - 1) as f64)]
                })
                .collect()
        })
        .collect()
}

fn equalizer() -> Vec<String> {
    let glyphs: Vec<char> = "▁▂▃▄▅▆▇█".chars().collect();
    let mut rnd = Lcg(7);
    (0..12)
        .map(|_| (0..5).map(|_| glyphs[rnd.next() as usize % glyphs.len()]).collect())
        .collect()
}

fn scanner() -> Vec<String> {
    let cells = 7usize;
    let mut path: Vec<usize> = (0..cells).collect();
    path.extend((1..cells - 1).rev());
    path.iter()
        .enumerate()
        .map(|(i, &p)| {
            let mut s = vec![' '; cells];
            let prev = if i == 0 { path[path.len() - 1] } else { path[i - 1] };
            s[prev] = '·';
            s[p] = '▪';
            s.into_iter().collect()
        })
        .collect()
}

fn shimmer() -> Vec<String> {
    let cells = 8i32;
    let band: Vec<char> = "▒▓█▓▒".chars().collect();
    (0..cells + band.len() as i32)
        .map(|off| {
            let mut s = vec!['░'; cells as usize];
            for (i, &ch) in band.iter().enumerate() {
                let x = off - band.len() as i32 + 1 + i as i32;
                if (0..cells).contains(&x) {
                    s[x as usize] = ch;
                }
            }
            s.into_iter().collect()
        })
        .collect()
}

fn matrix() -> Vec<String> {
    let mut rnd = Lcg(3);
    (0..14)
        .map(|_| {
            (0..6)
                .map(|_| {
                    let byte = rnd.next() & 0xFF;
                    let byte = if byte == 0 { 1 } else { byte };
                    char::from_u32(0x2800 + byte as u32).unwrap_or('⠁')
                })
                .collect()
        })
        .collect()
}

/// Python's `round` is banker's rounding; the wave frames depend on it.
fn round_half_even(v: f64) -> usize {
    let floor = v.floor();
    let diff = v - floor;
    let n = if (diff - 0.5).abs() < f64::EPSILON {
        if (floor as i64) % 2 == 0 { floor } else { floor + 1.0 }
    } else {
        v.round()
    };
    n.max(0.0) as usize
}
