//! Spinner catalog: every spinner shipped with [yaspin] / cli-spinners plus tuiforge
//! originals. Generated by `tools/gen_spinners.py`; do not edit by hand.
//!
//! [yaspin]: https://github.com/pavdmyt/yaspin

use super::SpinnerDef;

/// yaspin `dots` - 10 frames @ 80 ms.
pub const DOTS: SpinnerDef = SpinnerDef {
    name: "dots",
    interval_ms: 80,
    frames: &["⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏"],
};

/// yaspin `dots2` - 8 frames @ 80 ms.
pub const DOTS2: SpinnerDef = SpinnerDef {
    name: "dots2",
    interval_ms: 80,
    frames: &["⣾", "⣽", "⣻", "⢿", "⡿", "⣟", "⣯", "⣷"],
};

/// yaspin `dots3` - 10 frames @ 80 ms.
pub const DOTS3: SpinnerDef = SpinnerDef {
    name: "dots3",
    interval_ms: 80,
    frames: &["⠋", "⠙", "⠚", "⠞", "⠖", "⠦", "⠴", "⠲", "⠳", "⠓"],
};

/// yaspin `dots4` - 14 frames @ 80 ms.
pub const DOTS4: SpinnerDef = SpinnerDef {
    name: "dots4",
    interval_ms: 80,
    frames: &[
        "⠄", "⠆", "⠇", "⠋", "⠙", "⠸", "⠰", "⠠", "⠰", "⠸", "⠙", "⠋", "⠇", "⠆",
    ],
};

/// yaspin `dots5` - 17 frames @ 80 ms.
pub const DOTS5: SpinnerDef = SpinnerDef {
    name: "dots5",
    interval_ms: 80,
    frames: &[
        "⠋", "⠙", "⠚", "⠒", "⠂", "⠂", "⠒", "⠲", "⠴", "⠦", "⠖", "⠒", "⠐", "⠐", "⠒", "⠓", "⠋",
    ],
};

/// yaspin `dots6` - 24 frames @ 80 ms.
pub const DOTS6: SpinnerDef = SpinnerDef {
    name: "dots6",
    interval_ms: 80,
    frames: &[
        "⠁", "⠉", "⠙", "⠚", "⠒", "⠂", "⠂", "⠒", "⠲", "⠴", "⠤", "⠄", "⠄", "⠤", "⠴", "⠲", "⠒", "⠂",
        "⠂", "⠒", "⠚", "⠙", "⠉", "⠁",
    ],
};

/// yaspin `dots7` - 24 frames @ 80 ms.
pub const DOTS7: SpinnerDef = SpinnerDef {
    name: "dots7",
    interval_ms: 80,
    frames: &[
        "⠈", "⠉", "⠋", "⠓", "⠒", "⠐", "⠐", "⠒", "⠖", "⠦", "⠤", "⠠", "⠠", "⠤", "⠦", "⠖", "⠒", "⠐",
        "⠐", "⠒", "⠓", "⠋", "⠉", "⠈",
    ],
};

/// yaspin `dots8` - 29 frames @ 80 ms.
pub const DOTS8: SpinnerDef = SpinnerDef {
    name: "dots8",
    interval_ms: 80,
    frames: &[
        "⠁", "⠁", "⠉", "⠙", "⠚", "⠒", "⠂", "⠂", "⠒", "⠲", "⠴", "⠤", "⠄", "⠄", "⠤", "⠠", "⠠", "⠤",
        "⠦", "⠖", "⠒", "⠐", "⠐", "⠒", "⠓", "⠋", "⠉", "⠈", "⠈",
    ],
};

/// yaspin `dots9` - 8 frames @ 80 ms.
pub const DOTS9: SpinnerDef = SpinnerDef {
    name: "dots9",
    interval_ms: 80,
    frames: &["⢹", "⢺", "⢼", "⣸", "⣇", "⡧", "⡗", "⡏"],
};

/// yaspin `dots10` - 7 frames @ 80 ms.
pub const DOTS10: SpinnerDef = SpinnerDef {
    name: "dots10",
    interval_ms: 80,
    frames: &["⢄", "⢂", "⢁", "⡁", "⡈", "⡐", "⡠"],
};

/// yaspin `dots11` - 8 frames @ 100 ms.
pub const DOTS11: SpinnerDef = SpinnerDef {
    name: "dots11",
    interval_ms: 100,
    frames: &["⠁", "⠂", "⠄", "⡀", "⢀", "⠠", "⠐", "⠈"],
};

/// yaspin `dots12` - 56 frames @ 80 ms.
pub const DOTS12: SpinnerDef = SpinnerDef {
    name: "dots12",
    interval_ms: 80,
    frames: &[
        "⢀⠀", "⡀⠀", "⠄⠀", "⢂⠀", "⡂⠀", "⠅⠀", "⢃⠀", "⡃⠀", "⠍⠀", "⢋⠀", "⡋⠀", "⠍⠁", "⢋⠁", "⡋⠁", "⠍⠉",
        "⠋⠉", "⠋⠉", "⠉⠙", "⠉⠙", "⠉⠩", "⠈⢙", "⠈⡙", "⢈⠩", "⡀⢙", "⠄⡙", "⢂⠩", "⡂⢘", "⠅⡘", "⢃⠨", "⡃⢐",
        "⠍⡐", "⢋⠠", "⡋⢀", "⠍⡁", "⢋⠁", "⡋⠁", "⠍⠉", "⠋⠉", "⠋⠉", "⠉⠙", "⠉⠙", "⠉⠩", "⠈⢙", "⠈⡙", "⠈⠩",
        "⠀⢙", "⠀⡙", "⠀⠩", "⠀⢘", "⠀⡘", "⠀⠨", "⠀⢐", "⠀⡐", "⠀⠠", "⠀⢀", "⠀⡀",
    ],
};

/// yaspin `dots13` - 8 frames @ 80 ms.
pub const DOTS13: SpinnerDef = SpinnerDef {
    name: "dots13",
    interval_ms: 80,
    frames: &["⣼", "⣹", "⢻", "⠿", "⡟", "⣏", "⣧", "⣶"],
};

/// yaspin `dots14` - 12 frames @ 80 ms.
pub const DOTS14: SpinnerDef = SpinnerDef {
    name: "dots14",
    interval_ms: 80,
    frames: &[
        "⠉⠉", "⠈⠙", "⠀⠹", "⠀⢸", "⠀⣰", "⢀⣠", "⣀⣀", "⣄⡀", "⣆⠀", "⡇⠀", "⠏⠀", "⠋⠁",
    ],
};

/// yaspin `dots8Bit` - 256 frames @ 80 ms.
pub const DOTS8BIT: SpinnerDef = SpinnerDef {
    name: "dots8Bit",
    interval_ms: 80,
    frames: &[
        "⠀", "⠁", "⠂", "⠃", "⠄", "⠅", "⠆", "⠇", "⡀", "⡁", "⡂", "⡃", "⡄", "⡅", "⡆", "⡇", "⠈", "⠉",
        "⠊", "⠋", "⠌", "⠍", "⠎", "⠏", "⡈", "⡉", "⡊", "⡋", "⡌", "⡍", "⡎", "⡏", "⠐", "⠑", "⠒", "⠓",
        "⠔", "⠕", "⠖", "⠗", "⡐", "⡑", "⡒", "⡓", "⡔", "⡕", "⡖", "⡗", "⠘", "⠙", "⠚", "⠛", "⠜", "⠝",
        "⠞", "⠟", "⡘", "⡙", "⡚", "⡛", "⡜", "⡝", "⡞", "⡟", "⠠", "⠡", "⠢", "⠣", "⠤", "⠥", "⠦", "⠧",
        "⡠", "⡡", "⡢", "⡣", "⡤", "⡥", "⡦", "⡧", "⠨", "⠩", "⠪", "⠫", "⠬", "⠭", "⠮", "⠯", "⡨", "⡩",
        "⡪", "⡫", "⡬", "⡭", "⡮", "⡯", "⠰", "⠱", "⠲", "⠳", "⠴", "⠵", "⠶", "⠷", "⡰", "⡱", "⡲", "⡳",
        "⡴", "⡵", "⡶", "⡷", "⠸", "⠹", "⠺", "⠻", "⠼", "⠽", "⠾", "⠿", "⡸", "⡹", "⡺", "⡻", "⡼", "⡽",
        "⡾", "⡿", "⢀", "⢁", "⢂", "⢃", "⢄", "⢅", "⢆", "⢇", "⣀", "⣁", "⣂", "⣃", "⣄", "⣅", "⣆", "⣇",
        "⢈", "⢉", "⢊", "⢋", "⢌", "⢍", "⢎", "⢏", "⣈", "⣉", "⣊", "⣋", "⣌", "⣍", "⣎", "⣏", "⢐", "⢑",
        "⢒", "⢓", "⢔", "⢕", "⢖", "⢗", "⣐", "⣑", "⣒", "⣓", "⣔", "⣕", "⣖", "⣗", "⢘", "⢙", "⢚", "⢛",
        "⢜", "⢝", "⢞", "⢟", "⣘", "⣙", "⣚", "⣛", "⣜", "⣝", "⣞", "⣟", "⢠", "⢡", "⢢", "⢣", "⢤", "⢥",
        "⢦", "⢧", "⣠", "⣡", "⣢", "⣣", "⣤", "⣥", "⣦", "⣧", "⢨", "⢩", "⢪", "⢫", "⢬", "⢭", "⢮", "⢯",
        "⣨", "⣩", "⣪", "⣫", "⣬", "⣭", "⣮", "⣯", "⢰", "⢱", "⢲", "⢳", "⢴", "⢵", "⢶", "⢷", "⣰", "⣱",
        "⣲", "⣳", "⣴", "⣵", "⣶", "⣷", "⢸", "⢹", "⢺", "⢻", "⢼", "⢽", "⢾", "⢿", "⣸", "⣹", "⣺", "⣻",
        "⣼", "⣽", "⣾", "⣿",
    ],
};

/// yaspin `dotsCircle` - 8 frames @ 80 ms.
pub const DOTS_CIRCLE: SpinnerDef = SpinnerDef {
    name: "dotsCircle",
    interval_ms: 80,
    frames: &["⢎ ", "⠎⠁", "⠊⠑", "⠈⠱", " ⡱", "⢀⡰", "⢄⡠", "⢆⡀"],
};

/// yaspin `sand` - 35 frames @ 80 ms.
pub const SAND: SpinnerDef = SpinnerDef {
    name: "sand",
    interval_ms: 80,
    frames: &[
        "⠁", "⠂", "⠄", "⡀", "⡈", "⡐", "⡠", "⣀", "⣁", "⣂", "⣄", "⣌", "⣔", "⣤", "⣥", "⣦", "⣮", "⣶",
        "⣷", "⣿", "⡿", "⠿", "⢟", "⠟", "⡛", "⠛", "⠫", "⢋", "⠋", "⠍", "⡉", "⠉", "⠑", "⠡", "⢁",
    ],
};

/// yaspin `line` - 4 frames @ 130 ms.
pub const LINE: SpinnerDef = SpinnerDef {
    name: "line",
    interval_ms: 130,
    frames: &["-", "\\", "|", "/"],
};

/// yaspin `line2` - 6 frames @ 100 ms.
pub const LINE2: SpinnerDef = SpinnerDef {
    name: "line2",
    interval_ms: 100,
    frames: &["⠂", "-", "–", "—", "–", "-"],
};

/// yaspin `rollingLine` - 8 frames @ 80 ms.
pub const ROLLING_LINE: SpinnerDef = SpinnerDef {
    name: "rollingLine",
    interval_ms: 80,
    frames: &["/  ", " - ", " \\ ", "  |", "  |", " \\ ", " - ", "/  "],
};

/// yaspin `pipe` - 8 frames @ 100 ms.
pub const PIPE: SpinnerDef = SpinnerDef {
    name: "pipe",
    interval_ms: 100,
    frames: &["┤", "┘", "┴", "└", "├", "┌", "┬", "┐"],
};

/// yaspin `simpleDots` - 4 frames @ 400 ms.
pub const SIMPLE_DOTS: SpinnerDef = SpinnerDef {
    name: "simpleDots",
    interval_ms: 400,
    frames: &[".  ", ".. ", "...", "   "],
};

/// yaspin `simpleDotsScrolling` - 6 frames @ 200 ms.
pub const SIMPLE_DOTS_SCROLLING: SpinnerDef = SpinnerDef {
    name: "simpleDotsScrolling",
    interval_ms: 200,
    frames: &[".  ", ".. ", "...", " ..", "  .", "   "],
};

/// yaspin `star` - 6 frames @ 70 ms.
pub const STAR: SpinnerDef = SpinnerDef {
    name: "star",
    interval_ms: 70,
    frames: &["✶", "✸", "✹", "✺", "✹", "✷"],
};

/// yaspin `star2` - 3 frames @ 80 ms.
pub const STAR2: SpinnerDef = SpinnerDef {
    name: "star2",
    interval_ms: 80,
    frames: &["+", "x", "*"],
};

/// yaspin `flip` - 12 frames @ 70 ms.
pub const FLIP: SpinnerDef = SpinnerDef {
    name: "flip",
    interval_ms: 70,
    frames: &["_", "_", "_", "-", "`", "`", "'", "´", "-", "_", "_", "_"],
};

/// yaspin `hamburger` - 3 frames @ 100 ms.
pub const HAMBURGER: SpinnerDef = SpinnerDef {
    name: "hamburger",
    interval_ms: 100,
    frames: &["☱", "☲", "☴"],
};

/// yaspin `growVertical` - 10 frames @ 120 ms.
pub const GROW_VERTICAL: SpinnerDef = SpinnerDef {
    name: "growVertical",
    interval_ms: 120,
    frames: &["▁", "▃", "▄", "▅", "▆", "▇", "▆", "▅", "▄", "▃"],
};

/// yaspin `growHorizontal` - 12 frames @ 120 ms.
pub const GROW_HORIZONTAL: SpinnerDef = SpinnerDef {
    name: "growHorizontal",
    interval_ms: 120,
    frames: &["▏", "▎", "▍", "▌", "▋", "▊", "▉", "▊", "▋", "▌", "▍", "▎"],
};

/// yaspin `balloon` - 7 frames @ 140 ms.
pub const BALLOON: SpinnerDef = SpinnerDef {
    name: "balloon",
    interval_ms: 140,
    frames: &[" ", ".", "o", "O", "@", "*", " "],
};

/// yaspin `balloon2` - 7 frames @ 120 ms.
pub const BALLOON2: SpinnerDef = SpinnerDef {
    name: "balloon2",
    interval_ms: 120,
    frames: &[".", "o", "O", "°", "O", "o", "."],
};

/// yaspin `noise` - 3 frames @ 100 ms.
pub const NOISE: SpinnerDef = SpinnerDef {
    name: "noise",
    interval_ms: 100,
    frames: &["▓", "▒", "░"],
};

/// yaspin `bounce` - 4 frames @ 120 ms.
pub const BOUNCE: SpinnerDef = SpinnerDef {
    name: "bounce",
    interval_ms: 120,
    frames: &["⠁", "⠂", "⠄", "⠂"],
};

/// yaspin `boxBounce` - 4 frames @ 120 ms.
pub const BOX_BOUNCE: SpinnerDef = SpinnerDef {
    name: "boxBounce",
    interval_ms: 120,
    frames: &["▖", "▘", "▝", "▗"],
};

/// yaspin `boxBounce2` - 4 frames @ 100 ms.
pub const BOX_BOUNCE2: SpinnerDef = SpinnerDef {
    name: "boxBounce2",
    interval_ms: 100,
    frames: &["▌", "▀", "▐", "▄"],
};

/// yaspin `triangle` - 4 frames @ 50 ms.
pub const TRIANGLE: SpinnerDef = SpinnerDef {
    name: "triangle",
    interval_ms: 50,
    frames: &["◢", "◣", "◤", "◥"],
};

/// yaspin `binary` - 10 frames @ 80 ms.
pub const BINARY: SpinnerDef = SpinnerDef {
    name: "binary",
    interval_ms: 80,
    frames: &[
        "010010", "001100", "100101", "111010", "111101", "010111", "101011", "111000", "110011",
        "110101",
    ],
};

/// yaspin `arc` - 6 frames @ 100 ms.
pub const ARC: SpinnerDef = SpinnerDef {
    name: "arc",
    interval_ms: 100,
    frames: &["◜", "◠", "◝", "◞", "◡", "◟"],
};

/// yaspin `circle` - 3 frames @ 120 ms.
pub const CIRCLE: SpinnerDef = SpinnerDef {
    name: "circle",
    interval_ms: 120,
    frames: &["◡", "⊙", "◠"],
};

/// yaspin `squareCorners` - 4 frames @ 180 ms.
pub const SQUARE_CORNERS: SpinnerDef = SpinnerDef {
    name: "squareCorners",
    interval_ms: 180,
    frames: &["◰", "◳", "◲", "◱"],
};

/// yaspin `circleQuarters` - 4 frames @ 120 ms.
pub const CIRCLE_QUARTERS: SpinnerDef = SpinnerDef {
    name: "circleQuarters",
    interval_ms: 120,
    frames: &["◴", "◷", "◶", "◵"],
};

/// yaspin `circleHalves` - 4 frames @ 50 ms.
pub const CIRCLE_HALVES: SpinnerDef = SpinnerDef {
    name: "circleHalves",
    interval_ms: 50,
    frames: &["◐", "◓", "◑", "◒"],
};

/// yaspin `squish` - 2 frames @ 100 ms.
pub const SQUISH: SpinnerDef = SpinnerDef {
    name: "squish",
    interval_ms: 100,
    frames: &["╫", "╪"],
};

/// yaspin `toggle` - 2 frames @ 250 ms.
pub const TOGGLE: SpinnerDef = SpinnerDef {
    name: "toggle",
    interval_ms: 250,
    frames: &["⊶", "⊷"],
};

/// yaspin `toggle2` - 2 frames @ 80 ms.
pub const TOGGLE2: SpinnerDef = SpinnerDef {
    name: "toggle2",
    interval_ms: 80,
    frames: &["▫", "▪"],
};

/// yaspin `toggle3` - 2 frames @ 120 ms.
pub const TOGGLE3: SpinnerDef = SpinnerDef {
    name: "toggle3",
    interval_ms: 120,
    frames: &["□", "■"],
};

/// yaspin `toggle4` - 4 frames @ 100 ms.
pub const TOGGLE4: SpinnerDef = SpinnerDef {
    name: "toggle4",
    interval_ms: 100,
    frames: &["■", "□", "▪", "▫"],
};

/// yaspin `toggle5` - 2 frames @ 100 ms.
pub const TOGGLE5: SpinnerDef = SpinnerDef {
    name: "toggle5",
    interval_ms: 100,
    frames: &["▮", "▯"],
};

/// yaspin `toggle6` - 2 frames @ 300 ms.
pub const TOGGLE6: SpinnerDef = SpinnerDef {
    name: "toggle6",
    interval_ms: 300,
    frames: &["ဝ", "၀"],
};

/// yaspin `toggle7` - 2 frames @ 80 ms.
pub const TOGGLE7: SpinnerDef = SpinnerDef {
    name: "toggle7",
    interval_ms: 80,
    frames: &["⦾", "⦿"],
};

/// yaspin `toggle8` - 2 frames @ 100 ms.
pub const TOGGLE8: SpinnerDef = SpinnerDef {
    name: "toggle8",
    interval_ms: 100,
    frames: &["◍", "◌"],
};

/// yaspin `toggle9` - 2 frames @ 100 ms.
pub const TOGGLE9: SpinnerDef = SpinnerDef {
    name: "toggle9",
    interval_ms: 100,
    frames: &["◉", "◎"],
};

/// yaspin `toggle10` - 3 frames @ 100 ms.
pub const TOGGLE10: SpinnerDef = SpinnerDef {
    name: "toggle10",
    interval_ms: 100,
    frames: &["㊂", "㊀", "㊁"],
};

/// yaspin `toggle11` - 2 frames @ 50 ms.
pub const TOGGLE11: SpinnerDef = SpinnerDef {
    name: "toggle11",
    interval_ms: 50,
    frames: &["⧇", "⧆"],
};

/// yaspin `toggle12` - 2 frames @ 120 ms.
pub const TOGGLE12: SpinnerDef = SpinnerDef {
    name: "toggle12",
    interval_ms: 120,
    frames: &["☗", "☖"],
};

/// yaspin `toggle13` - 3 frames @ 80 ms.
pub const TOGGLE13: SpinnerDef = SpinnerDef {
    name: "toggle13",
    interval_ms: 80,
    frames: &["=", "*", "-"],
};

/// yaspin `arrow` - 8 frames @ 100 ms.
pub const ARROW: SpinnerDef = SpinnerDef {
    name: "arrow",
    interval_ms: 100,
    frames: &["←", "↖", "↑", "↗", "→", "↘", "↓", "↙"],
};

/// yaspin `arrow2` - 8 frames @ 80 ms.
pub const ARROW2: SpinnerDef = SpinnerDef {
    name: "arrow2",
    interval_ms: 80,
    frames: &["⬆️ ", "↗️ ", "➡️ ", "↘️ ", "⬇️ ", "↙️ ", "⬅️ ", "↖️ "],
};

/// yaspin `arrow3` - 6 frames @ 120 ms.
pub const ARROW3: SpinnerDef = SpinnerDef {
    name: "arrow3",
    interval_ms: 120,
    frames: &["▹▹▹▹▹", "▸▹▹▹▹", "▹▸▹▹▹", "▹▹▸▹▹", "▹▹▹▸▹", "▹▹▹▹▸"],
};

/// yaspin `bouncingBar` - 16 frames @ 80 ms.
pub const BOUNCING_BAR: SpinnerDef = SpinnerDef {
    name: "bouncingBar",
    interval_ms: 80,
    frames: &[
        "[    ]", "[=   ]", "[==  ]", "[=== ]", "[====]", "[ ===]", "[  ==]", "[   =]", "[    ]",
        "[   =]", "[  ==]", "[ ===]", "[====]", "[=== ]", "[==  ]", "[=   ]",
    ],
};

/// yaspin `bouncingBall` - 10 frames @ 80 ms.
pub const BOUNCING_BALL: SpinnerDef = SpinnerDef {
    name: "bouncingBall",
    interval_ms: 80,
    frames: &[
        "( ●    )",
        "(  ●   )",
        "(   ●  )",
        "(    ● )",
        "(     ●)",
        "(    ● )",
        "(   ●  )",
        "(  ●   )",
        "( ●    )",
        "(●     )",
    ],
};

/// yaspin `smiley` - 2 frames @ 200 ms.
pub const SMILEY: SpinnerDef = SpinnerDef {
    name: "smiley",
    interval_ms: 200,
    frames: &["😄 ", "😝 "],
};

/// yaspin `monkey` - 4 frames @ 300 ms.
pub const MONKEY: SpinnerDef = SpinnerDef {
    name: "monkey",
    interval_ms: 300,
    frames: &["🙈 ", "🙈 ", "🙉 ", "🙊 "],
};

/// yaspin `hearts` - 5 frames @ 100 ms.
pub const HEARTS: SpinnerDef = SpinnerDef {
    name: "hearts",
    interval_ms: 100,
    frames: &["💛 ", "💙 ", "💜 ", "💚 ", "💗 "],
};

/// yaspin `clock` - 12 frames @ 100 ms.
pub const CLOCK: SpinnerDef = SpinnerDef {
    name: "clock",
    interval_ms: 100,
    frames: &[
        "🕛 ", "🕐 ", "🕑 ", "🕒 ", "🕓 ", "🕔 ", "🕕 ", "🕖 ", "🕗 ", "🕘 ", "🕙 ", "🕚 ",
    ],
};

/// yaspin `earth` - 3 frames @ 180 ms.
pub const EARTH: SpinnerDef = SpinnerDef {
    name: "earth",
    interval_ms: 180,
    frames: &["🌍 ", "🌎 ", "🌏 "],
};

/// yaspin `material` - 92 frames @ 17 ms.
pub const MATERIAL: SpinnerDef = SpinnerDef {
    name: "material",
    interval_ms: 17,
    frames: &[
        "█▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁",
        "██▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁",
        "███▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁",
        "████▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁",
        "██████▁▁▁▁▁▁▁▁▁▁▁▁▁▁",
        "██████▁▁▁▁▁▁▁▁▁▁▁▁▁▁",
        "███████▁▁▁▁▁▁▁▁▁▁▁▁▁",
        "████████▁▁▁▁▁▁▁▁▁▁▁▁",
        "█████████▁▁▁▁▁▁▁▁▁▁▁",
        "█████████▁▁▁▁▁▁▁▁▁▁▁",
        "██████████▁▁▁▁▁▁▁▁▁▁",
        "███████████▁▁▁▁▁▁▁▁▁",
        "█████████████▁▁▁▁▁▁▁",
        "██████████████▁▁▁▁▁▁",
        "██████████████▁▁▁▁▁▁",
        "▁██████████████▁▁▁▁▁",
        "▁██████████████▁▁▁▁▁",
        "▁██████████████▁▁▁▁▁",
        "▁▁██████████████▁▁▁▁",
        "▁▁▁██████████████▁▁▁",
        "▁▁▁▁█████████████▁▁▁",
        "▁▁▁▁██████████████▁▁",
        "▁▁▁▁██████████████▁▁",
        "▁▁▁▁▁██████████████▁",
        "▁▁▁▁▁██████████████▁",
        "▁▁▁▁▁██████████████▁",
        "▁▁▁▁▁▁██████████████",
        "▁▁▁▁▁▁██████████████",
        "▁▁▁▁▁▁▁█████████████",
        "▁▁▁▁▁▁▁█████████████",
        "▁▁▁▁▁▁▁▁████████████",
        "▁▁▁▁▁▁▁▁████████████",
        "▁▁▁▁▁▁▁▁▁███████████",
        "▁▁▁▁▁▁▁▁▁███████████",
        "▁▁▁▁▁▁▁▁▁▁██████████",
        "▁▁▁▁▁▁▁▁▁▁██████████",
        "▁▁▁▁▁▁▁▁▁▁▁▁████████",
        "▁▁▁▁▁▁▁▁▁▁▁▁▁███████",
        "▁▁▁▁▁▁▁▁▁▁▁▁▁▁██████",
        "▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁█████",
        "▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁█████",
        "█▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁████",
        "██▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁███",
        "██▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁███",
        "███▁▁▁▁▁▁▁▁▁▁▁▁▁▁███",
        "████▁▁▁▁▁▁▁▁▁▁▁▁▁▁██",
        "█████▁▁▁▁▁▁▁▁▁▁▁▁▁▁█",
        "█████▁▁▁▁▁▁▁▁▁▁▁▁▁▁█",
        "██████▁▁▁▁▁▁▁▁▁▁▁▁▁█",
        "████████▁▁▁▁▁▁▁▁▁▁▁▁",
        "█████████▁▁▁▁▁▁▁▁▁▁▁",
        "█████████▁▁▁▁▁▁▁▁▁▁▁",
        "█████████▁▁▁▁▁▁▁▁▁▁▁",
        "█████████▁▁▁▁▁▁▁▁▁▁▁",
        "███████████▁▁▁▁▁▁▁▁▁",
        "████████████▁▁▁▁▁▁▁▁",
        "████████████▁▁▁▁▁▁▁▁",
        "██████████████▁▁▁▁▁▁",
        "██████████████▁▁▁▁▁▁",
        "▁██████████████▁▁▁▁▁",
        "▁██████████████▁▁▁▁▁",
        "▁▁▁█████████████▁▁▁▁",
        "▁▁▁▁▁████████████▁▁▁",
        "▁▁▁▁▁████████████▁▁▁",
        "▁▁▁▁▁▁███████████▁▁▁",
        "▁▁▁▁▁▁▁▁█████████▁▁▁",
        "▁▁▁▁▁▁▁▁█████████▁▁▁",
        "▁▁▁▁▁▁▁▁▁█████████▁▁",
        "▁▁▁▁▁▁▁▁▁█████████▁▁",
        "▁▁▁▁▁▁▁▁▁▁█████████▁",
        "▁▁▁▁▁▁▁▁▁▁▁████████▁",
        "▁▁▁▁▁▁▁▁▁▁▁████████▁",
        "▁▁▁▁▁▁▁▁▁▁▁▁███████▁",
        "▁▁▁▁▁▁▁▁▁▁▁▁███████▁",
        "▁▁▁▁▁▁▁▁▁▁▁▁▁███████",
        "▁▁▁▁▁▁▁▁▁▁▁▁▁███████",
        "▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁█████",
        "▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁████",
        "▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁████",
        "▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁████",
        "▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁███",
        "▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁███",
        "▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁██",
        "▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁██",
        "▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁██",
        "▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁█",
        "▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁█",
        "▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁█",
        "▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁",
        "▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁",
        "▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁",
        "▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁",
    ],
};

/// yaspin `moon` - 8 frames @ 80 ms.
pub const MOON: SpinnerDef = SpinnerDef {
    name: "moon",
    interval_ms: 80,
    frames: &["🌑 ", "🌒 ", "🌓 ", "🌔 ", "🌕 ", "🌖 ", "🌗 ", "🌘 "],
};

/// yaspin `runner` - 2 frames @ 140 ms.
pub const RUNNER: SpinnerDef = SpinnerDef {
    name: "runner",
    interval_ms: 140,
    frames: &["🚶 ", "🏃 "],
};

/// yaspin `pong` - 30 frames @ 80 ms.
pub const PONG: SpinnerDef = SpinnerDef {
    name: "pong",
    interval_ms: 80,
    frames: &[
        "▐⠂       ▌",
        "▐⠈       ▌",
        "▐ ⠂      ▌",
        "▐ ⠠      ▌",
        "▐  ⡀     ▌",
        "▐  ⠠     ▌",
        "▐   ⠂    ▌",
        "▐   ⠈    ▌",
        "▐    ⠂   ▌",
        "▐    ⠠   ▌",
        "▐     ⡀  ▌",
        "▐     ⠠  ▌",
        "▐      ⠂ ▌",
        "▐      ⠈ ▌",
        "▐       ⠂▌",
        "▐       ⠠▌",
        "▐       ⡀▌",
        "▐      ⠠ ▌",
        "▐      ⠂ ▌",
        "▐     ⠈  ▌",
        "▐     ⠂  ▌",
        "▐    ⠠   ▌",
        "▐    ⡀   ▌",
        "▐   ⠠    ▌",
        "▐   ⠂    ▌",
        "▐  ⠈     ▌",
        "▐  ⠂     ▌",
        "▐ ⠠      ▌",
        "▐ ⡀      ▌",
        "▐⠠       ▌",
    ],
};

/// yaspin `shark` - 26 frames @ 120 ms.
pub const SHARK: SpinnerDef = SpinnerDef {
    name: "shark",
    interval_ms: 120,
    frames: &[
        "▐|\\____________▌",
        "▐_|\\___________▌",
        "▐__|\\__________▌",
        "▐___|\\_________▌",
        "▐____|\\________▌",
        "▐_____|\\_______▌",
        "▐______|\\______▌",
        "▐_______|\\_____▌",
        "▐________|\\____▌",
        "▐_________|\\___▌",
        "▐__________|\\__▌",
        "▐___________|\\_▌",
        "▐____________|\\▌",
        "▐____________/|▌",
        "▐___________/|_▌",
        "▐__________/|__▌",
        "▐_________/|___▌",
        "▐________/|____▌",
        "▐_______/|_____▌",
        "▐______/|______▌",
        "▐_____/|_______▌",
        "▐____/|________▌",
        "▐___/|_________▌",
        "▐__/|__________▌",
        "▐_/|___________▌",
        "▐/|____________▌",
    ],
};

/// yaspin `dqpb` - 4 frames @ 100 ms.
pub const DQPB: SpinnerDef = SpinnerDef {
    name: "dqpb",
    interval_ms: 100,
    frames: &["d", "q", "p", "b"],
};

/// yaspin `weather` - 23 frames @ 100 ms.
pub const WEATHER: SpinnerDef = SpinnerDef {
    name: "weather",
    interval_ms: 100,
    frames: &[
        "☀️ ", "☀️ ", "☀️ ", "🌤 ", "⛅️ ", "🌥 ", "☁️ ", "🌧 ", "🌨 ", "🌧 ", "🌨 ", "🌧 ", "🌨 ", "⛈ ",
        "🌨 ", "🌧 ", "🌨 ", "☁️ ", "🌥 ", "⛅️ ", "🌤 ", "☀️ ", "☀️ ",
    ],
};

/// yaspin `christmas` - 2 frames @ 400 ms.
pub const CHRISTMAS: SpinnerDef = SpinnerDef {
    name: "christmas",
    interval_ms: 400,
    frames: &["🌲", "🎄"],
};

/// yaspin `grenade` - 14 frames @ 80 ms.
pub const GRENADE: SpinnerDef = SpinnerDef {
    name: "grenade",
    interval_ms: 80,
    frames: &[
        "،  ", "′  ", " ´ ", " ‾ ", "  ⸌", "  ⸊", "  |", "  ⁎", "  ⁕", " ෴ ", "  ⁓", "   ", "   ",
        "   ",
    ],
};

/// yaspin `point` - 5 frames @ 125 ms.
pub const POINT: SpinnerDef = SpinnerDef {
    name: "point",
    interval_ms: 125,
    frames: &["∙∙∙", "●∙∙", "∙●∙", "∙∙●", "∙∙∙"],
};

/// yaspin `layer` - 3 frames @ 150 ms.
pub const LAYER: SpinnerDef = SpinnerDef {
    name: "layer",
    interval_ms: 150,
    frames: &["-", "=", "≡"],
};

/// yaspin `betaWave` - 7 frames @ 80 ms.
pub const BETA_WAVE: SpinnerDef = SpinnerDef {
    name: "betaWave",
    interval_ms: 80,
    frames: &[
        "ρββββββ",
        "βρβββββ",
        "ββρββββ",
        "βββρβββ",
        "ββββρββ",
        "βββββρβ",
        "ββββββρ",
    ],
};

/// yaspin `fingerDance` - 6 frames @ 160 ms.
pub const FINGER_DANCE: SpinnerDef = SpinnerDef {
    name: "fingerDance",
    interval_ms: 160,
    frames: &["🤘 ", "🤟 ", "🖖 ", "✋ ", "🤚 ", "👆 "],
};

/// yaspin `fistBump` - 7 frames @ 80 ms.
pub const FIST_BUMP: SpinnerDef = SpinnerDef {
    name: "fistBump",
    interval_ms: 80,
    frames: &[
        "🤜　　　　🤛 ",
        "🤜　　　　🤛 ",
        "🤜　　　　🤛 ",
        "　🤜　　🤛　 ",
        "　　🤜🤛　　 ",
        "　🤜✨🤛　　 ",
        "🤜　✨　🤛　 ",
    ],
};

/// yaspin `soccerHeader` - 12 frames @ 80 ms.
pub const SOCCER_HEADER: SpinnerDef = SpinnerDef {
    name: "soccerHeader",
    interval_ms: 80,
    frames: &[
        " 🧑⚽️       🧑 ",
        "🧑  ⚽️      🧑 ",
        "🧑   ⚽️     🧑 ",
        "🧑    ⚽️    🧑 ",
        "🧑     ⚽️   🧑 ",
        "🧑      ⚽️  🧑 ",
        "🧑       ⚽️🧑  ",
        "🧑      ⚽️  🧑 ",
        "🧑     ⚽️   🧑 ",
        "🧑    ⚽️    🧑 ",
        "🧑   ⚽️     🧑 ",
        "🧑  ⚽️      🧑 ",
    ],
};

/// yaspin `mindblown` - 14 frames @ 160 ms.
pub const MINDBLOWN: SpinnerDef = SpinnerDef {
    name: "mindblown",
    interval_ms: 160,
    frames: &[
        "😐 ", "😐 ", "😮 ", "😮 ", "😦 ", "😦 ", "😧 ", "😧 ", "🤯 ", "💥 ", "✨ ", "　 ", "　 ",
        "　 ",
    ],
};

/// yaspin `speaker` - 4 frames @ 160 ms.
pub const SPEAKER: SpinnerDef = SpinnerDef {
    name: "speaker",
    interval_ms: 160,
    frames: &["🔈 ", "🔉 ", "🔊 ", "🔉 "],
};

/// yaspin `orangePulse` - 5 frames @ 100 ms.
pub const ORANGE_PULSE: SpinnerDef = SpinnerDef {
    name: "orangePulse",
    interval_ms: 100,
    frames: &["🔸 ", "🔶 ", "🟠 ", "🟠 ", "🔶 "],
};

/// yaspin `bluePulse` - 5 frames @ 100 ms.
pub const BLUE_PULSE: SpinnerDef = SpinnerDef {
    name: "bluePulse",
    interval_ms: 100,
    frames: &["🔹 ", "🔷 ", "🔵 ", "🔵 ", "🔷 "],
};

/// yaspin `orangeBluePulse` - 10 frames @ 100 ms.
pub const ORANGE_BLUE_PULSE: SpinnerDef = SpinnerDef {
    name: "orangeBluePulse",
    interval_ms: 100,
    frames: &[
        "🔸 ", "🔶 ", "🟠 ", "🟠 ", "🔶 ", "🔹 ", "🔷 ", "🔵 ", "🔵 ", "🔷 ",
    ],
};

/// yaspin `timeTravel` - 12 frames @ 100 ms.
pub const TIME_TRAVEL: SpinnerDef = SpinnerDef {
    name: "timeTravel",
    interval_ms: 100,
    frames: &[
        "🕛 ", "🕚 ", "🕙 ", "🕘 ", "🕗 ", "🕖 ", "🕕 ", "🕔 ", "🕓 ", "🕒 ", "🕑 ", "🕐 ",
    ],
};

/// yaspin `aesthetic` - 8 frames @ 80 ms.
pub const AESTHETIC: SpinnerDef = SpinnerDef {
    name: "aesthetic",
    interval_ms: 80,
    frames: &[
        "▰▱▱▱▱▱▱",
        "▰▰▱▱▱▱▱",
        "▰▰▰▱▱▱▱",
        "▰▰▰▰▱▱▱",
        "▰▰▰▰▰▱▱",
        "▰▰▰▰▰▰▱",
        "▰▰▰▰▰▰▰",
        "▰▱▱▱▱▱▱",
    ],
};

/// yaspin `dwarfFortress` - 133 frames @ 80 ms.
pub const DWARF_FORTRESS: SpinnerDef = SpinnerDef {
    name: "dwarfFortress",
    interval_ms: 80,
    frames: &[
        " ██████£££  ",
        "☺██████£££  ",
        "☺██████£££  ",
        "☺▓█████£££  ",
        "☺▓█████£££  ",
        "☺▒█████£££  ",
        "☺▒█████£££  ",
        "☺░█████£££  ",
        "☺░█████£££  ",
        "☺ █████£££  ",
        " ☺█████£££  ",
        " ☺█████£££  ",
        " ☺▓████£££  ",
        " ☺▓████£££  ",
        " ☺▒████£££  ",
        " ☺▒████£££  ",
        " ☺░████£££  ",
        " ☺░████£££  ",
        " ☺ ████£££  ",
        "  ☺████£££  ",
        "  ☺████£££  ",
        "  ☺▓███£££  ",
        "  ☺▓███£££  ",
        "  ☺▒███£££  ",
        "  ☺▒███£££  ",
        "  ☺░███£££  ",
        "  ☺░███£££  ",
        "  ☺ ███£££  ",
        "   ☺███£££  ",
        "   ☺███£££  ",
        "   ☺▓██£££  ",
        "   ☺▓██£££  ",
        "   ☺▒██£££  ",
        "   ☺▒██£££  ",
        "   ☺░██£££  ",
        "   ☺░██£££  ",
        "   ☺ ██£££  ",
        "    ☺██£££  ",
        "    ☺██£££  ",
        "    ☺▓█£££  ",
        "    ☺▓█£££  ",
        "    ☺▒█£££  ",
        "    ☺▒█£££  ",
        "    ☺░█£££  ",
        "    ☺░█£££  ",
        "    ☺ █£££  ",
        "     ☺█£££  ",
        "     ☺█£££  ",
        "     ☺▓£££  ",
        "     ☺▓£££  ",
        "     ☺▒£££  ",
        "     ☺▒£££  ",
        "     ☺░£££  ",
        "     ☺░£££  ",
        "     ☺ £££  ",
        "      ☺£££  ",
        "      ☺£££  ",
        "      ☺▓££  ",
        "      ☺▓££  ",
        "      ☺▒££  ",
        "      ☺▒££  ",
        "      ☺░££  ",
        "      ☺░££  ",
        "      ☺ ££  ",
        "       ☺££  ",
        "       ☺££  ",
        "       ☺▓£  ",
        "       ☺▓£  ",
        "       ☺▒£  ",
        "       ☺▒£  ",
        "       ☺░£  ",
        "       ☺░£  ",
        "       ☺ £  ",
        "        ☺£  ",
        "        ☺£  ",
        "        ☺▓  ",
        "        ☺▓  ",
        "        ☺▒  ",
        "        ☺▒  ",
        "        ☺░  ",
        "        ☺░  ",
        "        ☺   ",
        "        ☺  &",
        "        ☺ ☼&",
        "       ☺ ☼ &",
        "       ☺☼  &",
        "      ☺☼  & ",
        "      ‼   & ",
        "     ☺   &  ",
        "    ‼    &  ",
        "   ☺    &   ",
        "  ‼     &   ",
        " ☺     &    ",
        "‼      &    ",
        "      &     ",
        "      &     ",
        "     &   ░  ",
        "     &   ▒  ",
        "    &    ▓  ",
        "    &    £  ",
        "   &    ░£  ",
        "   &    ▒£  ",
        "  &     ▓£  ",
        "  &     ££  ",
        " &     ░££  ",
        " &     ▒££  ",
        "&      ▓££  ",
        "&      £££  ",
        "      ░£££  ",
        "      ▒£££  ",
        "      ▓£££  ",
        "      █£££  ",
        "     ░█£££  ",
        "     ▒█£££  ",
        "     ▓█£££  ",
        "     ██£££  ",
        "    ░██£££  ",
        "    ▒██£££  ",
        "    ▓██£££  ",
        "    ███£££  ",
        "   ░███£££  ",
        "   ▒███£££  ",
        "   ▓███£££  ",
        "   ████£££  ",
        "  ░████£££  ",
        "  ▒████£££  ",
        "  ▓████£££  ",
        "  █████£££  ",
        " ░█████£££  ",
        " ▒█████£££  ",
        " ▓█████£££  ",
        " ██████£££  ",
        " ██████£££  ",
    ],
};

/// yaspin `fish` - 27 frames @ 80 ms.
pub const FISH: SpinnerDef = SpinnerDef {
    name: "fish",
    interval_ms: 80,
    frames: &[
        "~~~~~~~~~~~~~~~~~~~~",
        "> ~~~~~~~~~~~~~~~~~~",
        "º> ~~~~~~~~~~~~~~~~~",
        "(º> ~~~~~~~~~~~~~~~~",
        "((º> ~~~~~~~~~~~~~~~",
        "<((º> ~~~~~~~~~~~~~~",
        "><((º> ~~~~~~~~~~~~~",
        " ><((º> ~~~~~~~~~~~~",
        "~ ><((º> ~~~~~~~~~~~",
        "~~ <>((º> ~~~~~~~~~~",
        "~~~ ><((º> ~~~~~~~~~",
        "~~~~ <>((º> ~~~~~~~~",
        "~~~~~ ><((º> ~~~~~~~",
        "~~~~~~ <>((º> ~~~~~~",
        "~~~~~~~ ><((º> ~~~~~",
        "~~~~~~~~ <>((º> ~~~~",
        "~~~~~~~~~ ><((º> ~~~",
        "~~~~~~~~~~ <>((º> ~~",
        "~~~~~~~~~~~ ><((º> ~",
        "~~~~~~~~~~~~ <>((º> ",
        "~~~~~~~~~~~~~ ><((º>",
        "~~~~~~~~~~~~~~ <>((º",
        "~~~~~~~~~~~~~~~ ><((",
        "~~~~~~~~~~~~~~~~ <>(",
        "~~~~~~~~~~~~~~~~~ ><",
        "~~~~~~~~~~~~~~~~~~ <",
        "~~~~~~~~~~~~~~~~~~~~",
    ],
};

/// tuiforge `sparkle` - 12 frames @ 90 ms.
pub const SPARKLE: SpinnerDef = SpinnerDef {
    name: "sparkle",
    interval_ms: 90,
    frames: &["✦", "✧", "✶", "✷", "✸", "✹", "✺", "✹", "✸", "✷", "✶", "✧"],
};

/// tuiforge `ring` - 8 frames @ 110 ms.
pub const RING: SpinnerDef = SpinnerDef {
    name: "ring",
    interval_ms: 110,
    frames: &["◌", "○", "◎", "◉", "●", "◉", "◎", "○"],
};

/// tuiforge `diamond` - 4 frames @ 180 ms.
pub const DIAMOND: SpinnerDef = SpinnerDef {
    name: "diamond",
    interval_ms: 180,
    frames: &["◇", "◈", "◆", "◈"],
};

/// tuiforge `squarePulse` - 6 frames @ 160 ms.
pub const SQUARE_PULSE: SpinnerDef = SpinnerDef {
    name: "squarePulse",
    interval_ms: 160,
    frames: &["□", "▢", "▣", "■", "▣", "▢"],
};

/// tuiforge `hourglass` - 2 frames @ 500 ms.
pub const HOURGLASS: SpinnerDef = SpinnerDef {
    name: "hourglass",
    interval_ms: 500,
    frames: &["⧖", "⧗"],
};

/// tuiforge `wave` - 14 frames @ 70 ms.
pub const WAVE: SpinnerDef = SpinnerDef {
    name: "wave",
    interval_ms: 70,
    frames: &[
        "▄▇▇▄▁▁",
        "▅▇▆▃▁▂",
        "▆▇▄▂▁▄",
        "▇▆▃▁▂▅",
        "▇▅▂▁▃▆",
        "▆▄▁▂▄▇",
        "▅▂▁▃▆▇",
        "▄▁▁▄▇▇",
        "▃▁▂▅▇▆",
        "▂▁▄▆▇▄",
        "▁▂▅▇▆▃",
        "▁▃▆▇▅▂",
        "▂▄▇▆▄▁",
        "▃▆▇▅▂▁",
    ],
};

/// tuiforge `equalizer` - 12 frames @ 110 ms.
pub const EQUALIZER: SpinnerDef = SpinnerDef {
    name: "equalizer",
    interval_ms: 110,
    frames: &[
        "▅▇▅▃▄",
        "▆▃▇▂▂",
        "▆▄▇▃▆",
        "▃▂▇▇▅",
        "▅▄█▃▆",
        "▁█▂▃▇",
        "▆▇▃▃▅",
        "▄▄▁▁▅",
        "█▇▅▆▇",
        "▇▇▁▃▂",
        "▂█▆▄▂",
        "▇▃▄▅▇",
    ],
};

/// tuiforge `scanner` - 12 frames @ 80 ms.
pub const SCANNER: SpinnerDef = SpinnerDef {
    name: "scanner",
    interval_ms: 80,
    frames: &[
        "▪·     ",
        "·▪     ",
        " ·▪    ",
        "  ·▪   ",
        "   ·▪  ",
        "    ·▪ ",
        "     ·▪",
        "     ▪·",
        "    ▪· ",
        "   ▪·  ",
        "  ▪·   ",
        " ▪·    ",
    ],
};

/// tuiforge `shimmer` - 13 frames @ 70 ms.
pub const SHIMMER: SpinnerDef = SpinnerDef {
    name: "shimmer",
    interval_ms: 70,
    frames: &[
        "▒░░░░░░░",
        "▓▒░░░░░░",
        "█▓▒░░░░░",
        "▓█▓▒░░░░",
        "▒▓█▓▒░░░",
        "░▒▓█▓▒░░",
        "░░▒▓█▓▒░",
        "░░░▒▓█▓▒",
        "░░░░▒▓█▓",
        "░░░░░▒▓█",
        "░░░░░░▒▓",
        "░░░░░░░▒",
        "░░░░░░░░",
    ],
};

/// tuiforge `dna` - 8 frames @ 120 ms.
pub const DNA: SpinnerDef = SpinnerDef {
    name: "dna",
    interval_ms: 120,
    frames: &[
        "●───○",
        " ●─○ ",
        "  ◍  ",
        " ○─● ",
        "○───●",
        " ○─● ",
        "  ◍  ",
        " ●─○ ",
    ],
};

/// tuiforge `matrix` - 14 frames @ 90 ms.
pub const MATRIX: SpinnerDef = SpinnerDef {
    name: "matrix",
    interval_ms: 90,
    frames: &[
        "⡓⣃⡽⡸⢎⢴",
        "⡍⢷⡈⠯⡭⡆",
        "⠽⠙⣥⡰⠤⡌",
        "⢻⢠⣣⡘⣼⡸",
        "⡴⣺⢌⢱⢕⡜",
        "⢯⢵⠲⠒⡓⣾",
        "⢓⣑⠣⠬⡅⣭",
        "⡌⣩⣉⢙⠍⡽",
        "⣿⣜⠁⠰⡑⡕",
        "⠬⡣⢠⢰⣇⡭",
        "⣮⣤⣌⠶⣐⠲",
        "⡀⢖⢑⣝⡃⡫",
        "⠦⢪⣘⡼⣖⠖",
        "⡵⠑⢦⡚⡊⡎",
    ],
};

/// tuiforge `brailleWave` - 4 frames @ 100 ms.
pub const BRAILLE_WAVE: SpinnerDef = SpinnerDef {
    name: "brailleWave",
    interval_ms: 100,
    frames: &["⣀⠤⠉", "⠤⠉⠤", "⠉⠤⣀", "⠤⣀⠤"],
};

/// The yaspin / cli-spinners set, in upstream order.
pub const YASPIN: &[&SpinnerDef] = &[
    &DOTS,
    &DOTS2,
    &DOTS3,
    &DOTS4,
    &DOTS5,
    &DOTS6,
    &DOTS7,
    &DOTS8,
    &DOTS9,
    &DOTS10,
    &DOTS11,
    &DOTS12,
    &DOTS13,
    &DOTS14,
    &DOTS8BIT,
    &DOTS_CIRCLE,
    &SAND,
    &LINE,
    &LINE2,
    &ROLLING_LINE,
    &PIPE,
    &SIMPLE_DOTS,
    &SIMPLE_DOTS_SCROLLING,
    &STAR,
    &STAR2,
    &FLIP,
    &HAMBURGER,
    &GROW_VERTICAL,
    &GROW_HORIZONTAL,
    &BALLOON,
    &BALLOON2,
    &NOISE,
    &BOUNCE,
    &BOX_BOUNCE,
    &BOX_BOUNCE2,
    &TRIANGLE,
    &BINARY,
    &ARC,
    &CIRCLE,
    &SQUARE_CORNERS,
    &CIRCLE_QUARTERS,
    &CIRCLE_HALVES,
    &SQUISH,
    &TOGGLE,
    &TOGGLE2,
    &TOGGLE3,
    &TOGGLE4,
    &TOGGLE5,
    &TOGGLE6,
    &TOGGLE7,
    &TOGGLE8,
    &TOGGLE9,
    &TOGGLE10,
    &TOGGLE11,
    &TOGGLE12,
    &TOGGLE13,
    &ARROW,
    &ARROW2,
    &ARROW3,
    &BOUNCING_BAR,
    &BOUNCING_BALL,
    &SMILEY,
    &MONKEY,
    &HEARTS,
    &CLOCK,
    &EARTH,
    &MATERIAL,
    &MOON,
    &RUNNER,
    &PONG,
    &SHARK,
    &DQPB,
    &WEATHER,
    &CHRISTMAS,
    &GRENADE,
    &POINT,
    &LAYER,
    &BETA_WAVE,
    &FINGER_DANCE,
    &FIST_BUMP,
    &SOCCER_HEADER,
    &MINDBLOWN,
    &SPEAKER,
    &ORANGE_PULSE,
    &BLUE_PULSE,
    &ORANGE_BLUE_PULSE,
    &TIME_TRAVEL,
    &AESTHETIC,
    &DWARF_FORTRESS,
    &FISH,
];

/// Spinners original to tuiforge.
pub const ORIGINALS: &[&SpinnerDef] = &[
    &SPARKLE,
    &RING,
    &DIAMOND,
    &SQUARE_PULSE,
    &HOURGLASS,
    &WAVE,
    &EQUALIZER,
    &SCANNER,
    &SHIMMER,
    &DNA,
    &MATRIX,
    &BRAILLE_WAVE,
];

/// Every spinner: [`YASPIN`] followed by [`ORIGINALS`].
pub const ALL: &[&SpinnerDef] = &[
    &DOTS,
    &DOTS2,
    &DOTS3,
    &DOTS4,
    &DOTS5,
    &DOTS6,
    &DOTS7,
    &DOTS8,
    &DOTS9,
    &DOTS10,
    &DOTS11,
    &DOTS12,
    &DOTS13,
    &DOTS14,
    &DOTS8BIT,
    &DOTS_CIRCLE,
    &SAND,
    &LINE,
    &LINE2,
    &ROLLING_LINE,
    &PIPE,
    &SIMPLE_DOTS,
    &SIMPLE_DOTS_SCROLLING,
    &STAR,
    &STAR2,
    &FLIP,
    &HAMBURGER,
    &GROW_VERTICAL,
    &GROW_HORIZONTAL,
    &BALLOON,
    &BALLOON2,
    &NOISE,
    &BOUNCE,
    &BOX_BOUNCE,
    &BOX_BOUNCE2,
    &TRIANGLE,
    &BINARY,
    &ARC,
    &CIRCLE,
    &SQUARE_CORNERS,
    &CIRCLE_QUARTERS,
    &CIRCLE_HALVES,
    &SQUISH,
    &TOGGLE,
    &TOGGLE2,
    &TOGGLE3,
    &TOGGLE4,
    &TOGGLE5,
    &TOGGLE6,
    &TOGGLE7,
    &TOGGLE8,
    &TOGGLE9,
    &TOGGLE10,
    &TOGGLE11,
    &TOGGLE12,
    &TOGGLE13,
    &ARROW,
    &ARROW2,
    &ARROW3,
    &BOUNCING_BAR,
    &BOUNCING_BALL,
    &SMILEY,
    &MONKEY,
    &HEARTS,
    &CLOCK,
    &EARTH,
    &MATERIAL,
    &MOON,
    &RUNNER,
    &PONG,
    &SHARK,
    &DQPB,
    &WEATHER,
    &CHRISTMAS,
    &GRENADE,
    &POINT,
    &LAYER,
    &BETA_WAVE,
    &FINGER_DANCE,
    &FIST_BUMP,
    &SOCCER_HEADER,
    &MINDBLOWN,
    &SPEAKER,
    &ORANGE_PULSE,
    &BLUE_PULSE,
    &ORANGE_BLUE_PULSE,
    &TIME_TRAVEL,
    &AESTHETIC,
    &DWARF_FORTRESS,
    &FISH,
    &SPARKLE,
    &RING,
    &DIAMOND,
    &SQUARE_PULSE,
    &HOURGLASS,
    &WAVE,
    &EQUALIZER,
    &SCANNER,
    &SHIMMER,
    &DNA,
    &MATRIX,
    &BRAILLE_WAVE,
];
