#!/usr/bin/env python3
"""Generate `tuiforge/src/widgets/spinner/spinners.rs`.

Sources: `tools/spinners.json` (yaspin's copy of cli-spinners, 90 spinners) plus the
tuiforge originals defined below. Re-run after editing either.
"""

import json
import math
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "tools" / "spinners.json"
OUT = ROOT / "tuiforge" / "src" / "widgets" / "spinner" / "spinners.rs"


def wave(n=7, cells=6, glyphs="▁▂▃▄▅▆▇"):
    out = []
    for f in range(n * 2):
        s = ""
        for c in range(cells):
            v = (math.sin((c / cells + f / (n * 2)) * 2 * math.pi) + 1) / 2
            s += glyphs[round(v * (len(glyphs) - 1))]
        out.append(s)
    return out


def lcg(seed):
    while True:
        seed = (seed * 1103515245 + 12345) & 0x7FFFFFFF
        yield seed >> 16


def equalizer(bars=5, frames=12, glyphs="▁▂▃▄▅▆▇█"):
    rnd = lcg(7)
    return ["".join(glyphs[next(rnd) % len(glyphs)] for _ in range(bars)) for _ in range(frames)]


def scanner(cells=7):
    path = list(range(cells)) + list(range(cells - 2, 0, -1))
    out = []
    for i, p in enumerate(path):
        s = [" "] * cells
        s[path[i - 1]] = "·"
        s[p] = "▪"
        out.append("".join(s))
    return out


def shimmer(cells=8, band="▒▓█▓▒"):
    out = []
    for off in range(cells + len(band)):
        s = ["░"] * cells
        for i, ch in enumerate(band):
            x = off - len(band) + 1 + i
            if 0 <= x < cells:
                s[x] = ch
        out.append("".join(s))
    return out


def matrix(cells=6, frames=14):
    rnd = lcg(3)
    return ["".join(chr(0x2800 + (next(rnd) & 0xFF or 1)) for _ in range(cells)) for _ in range(frames)]


# name -> (interval_ms, frames). Names are camelCase like cli-spinners.
ORIGINALS = {
    "sparkle": (90, ["✦", "✧", "✶", "✷", "✸", "✹", "✺", "✹", "✸", "✷", "✶", "✧"]),
    "ring": (110, ["◌", "○", "◎", "◉", "●", "◉", "◎", "○"]),
    "diamond": (180, ["◇", "◈", "◆", "◈"]),
    "squarePulse": (160, ["□", "▢", "▣", "■", "▣", "▢"]),
    "hourglass": (500, ["⧖", "⧗"]),
    "wave": (70, wave()),
    "equalizer": (110, equalizer()),
    "scanner": (80, scanner()),
    "shimmer": (70, shimmer()),
    "dna": (120, ["●───○", " ●─○ ", "  ◍  ", " ○─● ", "○───●", " ○─● ", "  ◍  ", " ●─○ "]),
    "matrix": (90, matrix()),
    "brailleWave": (100, ["⣀⠤⠉", "⠤⠉⠤", "⠉⠤⣀", "⠤⣀⠤"]),
}


def const_name(name):
    return re.sub(r"(?<=[a-z])(?=[A-Z])", "_", name).upper()


def rust_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def emit(name, interval, frames, origin):
    frames_src = ", ".join(rust_str(f) for f in frames)
    return (
        f"/// {origin} `{name}` - {len(frames)} frames @ {interval} ms.\n"
        f"pub const {const_name(name)}: SpinnerDef = SpinnerDef {{ name: {rust_str(name)}, interval_ms: {interval}, frames: &[{frames_src}] }};\n"
    )


def main():
    yaspin = json.loads(SRC.read_text(encoding="utf-8"))
    dup = set(yaspin) & set(ORIGINALS)
    assert not dup, f"original names clash with yaspin: {dup}"

    lines = [
        "//! Spinner catalog: every spinner shipped with [yaspin] / cli-spinners plus tuiforge",
        "//! originals. Generated by `tools/gen_spinners.py`; do not edit by hand.",
        "//!",
        "//! [yaspin]: https://github.com/pavdmyt/yaspin",
        "",
        "use super::SpinnerDef;",
        "",
    ]
    for name, spec in yaspin.items():
        lines.append(emit(name, spec["interval"], spec["frames"], "yaspin"))
    for name, (interval, frames) in ORIGINALS.items():
        lines.append(emit(name, interval, frames, "tuiforge"))

    def table(doc, const, names):
        refs = ", ".join(f"&{const_name(n)}" for n in names)
        return f"/// {doc}\npub const {const}: &[&SpinnerDef] = &[{refs}];\n"

    lines.append(table("The yaspin / cli-spinners set, in upstream order.", "YASPIN", list(yaspin)))
    lines.append(table("Spinners original to tuiforge.", "ORIGINALS", list(ORIGINALS)))
    lines.append(table("Every spinner: [`YASPIN`] followed by [`ORIGINALS`].", "ALL", list(yaspin) + list(ORIGINALS)))

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}: {len(yaspin)} yaspin + {len(ORIGINALS)} originals")


if __name__ == "__main__":
    main()
